/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.robertsmieja.gradle.template;

public class Library {
  public boolean someLibraryMethod() {
    return true;
  }
}
